#!/usr/bin/env bash
# We are to Configure nginix so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx

# Configures firewall to allow request through port 80
ufw allow 'Nginx HTTP'

echo 'Hello World' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart webserver after updating the service
service nginx start
