#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine in respect to the requirement given
# starr code

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  starr-frontend
        bind *:80
        mode http
        default_backend starr-backend
backend starr-backend
        balance roundrobin
        server 144060-web-01 54.146.79.137:80 check
        server 144060-web-02 54.152.191.29:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
