#!/usr/bin/env bash
# A script that contains the solutions to what is keeping your Ubuntu container Nginx installation from listening on port 80.
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
